### ISSUE TITLE
responsive

### ISSUE THREAD

**Issue by JCruzMi** [shahriyardx/easy-pil#1]
easy pil have a space-between?

**Comment by shahriyardx** [comment]
> easy pil have a space-between?

No it has a `_`

**Comment by JCruzMi** [comment]
I think it has a problem for large numbers. then i am looking for the best solution.

**Comment by shahriyardx** [comment]
Hey I think you meant to aligh something from right so texts start from the end. When you draw a text just set align="right" it will start from end
