### ISSUE TITLE
add shadow behind texts

### ISSUE THREAD

**Issue by ashroyxi** [shahriyardx/easy-pil#11]
texts are not always clearly visible because of the background picture. adding shadow is the proper solution in my opinion. how to?

**Comment by XordK** [comment]
You can do this yourself by pasting the same text on top of each other with an offset

**Comment by ashroyxi** [comment]
i switched to pillow, 
how to i set an "offset"

**Comment by XordK** [comment]
an offset is just the difference between two values. So to create a drop shadow you could paste the text in your shadow color and then paste your text again in your normal color 5 pixels above and to the left. This would imitate a drop shadow.

Those 5 pixels above and 5 pixels to the left are your offset.

Depending on your font size you may want to change the number of pixels in your offset.
