### ISSUE TITLE
AttributeError: 'Editor' object has no attribute 'multicolor_text'

### ISSUE THREAD

**Issue by VladVollar** [shahriyardx/easy-pil#13]
You have in rank card 2 example `background.multicolor_text((850, 30), texts=rank_level_texts, align="right")`, but it causes an error "AttributeError: 'Editor' object has no attribute 'multicolor_text'"

**Comment by shahriyardx** [comment]
its now multi_text
https://easy-pil.readthedocs.io/en/latest/easy_pil/easy_pil.editor.html#easy_pil.editor.Editor.resize
