### ISSUE TITLE
easy-pil not installing python 3.11

### ISSUE THREAD

**Issue by CringleySDays** [shahriyardx/easy-pil#15]
aiohttp was an issue to this and they seem to have patched it when I install aiohttp on its own, however when I still easy-pil, the error below. I'm not sure if I'm supposed to make a issue request at aiohttp themselves.

As much as I'd like to go to 3.10, for the performance boost 3.11, I'll prefer to use that. 

![image](https://user-images.githubusercontent.com/100538275/200647020-bce68059-3e34-4644-9024-ca86a3a37e7f.png)

**Comment by CringleySDays** [comment]
https://github.com/aio-libs/aiohttp/issues/6600 Issue patched apparenty, not sure where exactly I'm supposed to go

**Comment by CringleySDays** [comment]
I see, I'll wait for a version upgrade in the mean time 👍

**Comment by CringleySDays** [comment]
Any updates if easy-pil is compatbile with 3.11 after installing new version of aiohttp?

**Comment by shahriyardx** [comment]
> Any updates if easy-pil is compatbile with 3.11 after installing new version of aiohttp?

After taking a closer look. I can see that building subprocess requires you to have C++ installed on your computer. 
Its not this library.

**Comment by CringleySDays** [comment]
I need to install C++? I thought that dev tools itself from VS was enough. I presume you have tested this out

**Comment by shahriyardx** [comment]
> I need to install C++? I thought that dev tools itself from VS was enough. I presume you have tested this out

That should be enough. After a bit of research I found that aiohttp is still not compatible with 3.11 
- https://github.com/aio-libs/aiohttp/issues/7051
- https://pyreadiness.org/3.11/

Also in the lib's latest release 3.11 is not present as a clasifiers.  
![image](https://user-images.githubusercontent.com/40076722/204914065-4461fe26-7d98-44df-a3e4-a912fc1ae546.png)

**Comment by CringleySDays** [comment]
Oh? When I download aiohttp alone, it downloads fine automatically, have you downloaded the github version?

**Comment by CringleySDays** [comment]
![image](https://user-images.githubusercontent.com/100538275/205031650-dade090d-1023-4e1c-b533-9c84a5b39566.png)

**Comment by shahriyardx** [comment]
If manual install works then for now I have made installing aiohttp only on < 3.11

You can install it from the 3.11 branch using 
```sh
python3 -m pip install git+https://github.com/shahriyardx/easy-pil@3.11
```

Then you have to manually install `aiohttp` and it should work for now. 
And I will wait for aiohttp being toally compatible with 3.11 and the issue I mentioned is resolved.
