### ISSUE TITLE
Add save function 

### ISSUE THREAD

**Issue by nellle** [shahriyardx/easy-pil#2]
This is not difficult to do, but it would help a lot. Of course, I worked with the sources and added this function to myself, but I would like to see it in the library itself

**Comment by shahriyardx** [comment]
Will be added on next update.

**Comment by shahriyardx** [comment]
Now Editor class has a save function also I did some more improvements on other things like the rounded_corner has a offset because sometime it dont get perfectly rounded so setting a offset can fix it.
