### ISSUE TITLE
Python version 3.7 raises import error

### ISSUE THREAD

**Issue by madphysicist** [shahriyardx/easy-pil#3]
Comparing

https://github.com/shahriyardx/easy-pil/blob/cf259c0f9d370506d8d0bc2ef521f040467499a3/setup.py#L36

to

https://stackoverflow.com/q/70210001/2988730

Seems like 3.7 needs a tweak for full support.

**Comment by shahriyardx** [comment]
I have updated it. Should fix the issue

**Comment by madphysicist** [comment]
Looks good. The commit shows that almost every file was touched, probably because of line endings. Couple of comments:

1. The new requirement `typing-extensions==4.0.1` could be future-proofed using `>=`.
2. Would you consider using version tags in Git?

**Comment by shahriyardx** [comment]
> Looks good. The commit shows that almost every file was touched, probably because of line endings. Couple of comments:
> 
> 1. The new requirement `typing-extensions==4.0.1` could be future-proofed using `>=`.
> 2. Would you consider using version tags in Git?

Every file changed because I opened the folder using pycharm. And it somehow changed every line of code 🥴

For your suggestions you can do a PR with suggested changes.

**Comment by madphysicist** [comment]
I think I'll do that, but I won't be able to make tags on the master branch.

**Comment by madphysicist** [comment]
@shahriyardx. I've gone ahead and did some mods to the setup code in #4. Hope you like them.
