### ISSUE TITLE
Creating transparency areas instead of objects

### ISSUE THREAD

**Issue by Chitter777** [shahriyardx/easy-pil#30]
## Summary
Fix bug in easy_pil.Editor
## Reproduction Steps

1.  Install last version of easy_pil (0.3.0) and Python 3.11.3
2. Run code from the next paragraph
## Minimal Reproducible Code
```py
from easy_pil import Canvas, Editor
test_imag = Editor(Canvas((900, 200), color="#23272A"))
test_imag.rectangle((30, 120), width=700, height=40, fill="#494b4f", radius=20)
test_imag.bar(
    (30, 120),
    max_width=700,
    height=40,
    percentage=50,
    fill=5793266,  # warning
    radius=20,
)

test_imag.show()
```

### Expected Results
![expecter_result](https://cdn.discordapp.com/attachments/926402084117545050/1119310355571679273/test_xp.jpg)

### Actual Results
![actual_result](https://cdn.discordapp.com/attachments/926402084117545050/1119310273434628206/test_xp.jpg)

**Comment by shahriyardx** [comment]
The images are not showing can you update the issue with working image links
